"""document chunks store

Revision ID: 605775f630d8
Revises: d5b608e3fdd6
Create Date: 2026-10-01 22:41:03.826968
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.models


revision: str = '605775f630d8'
down_revision: str | None = 'd5b608e3fdd6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('dockey', sa.String(length=64), nullable=False),
    sa.Column('docname', sa.String(length=255), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('settings_md5', sa.String(length=64), nullable=True),
    sa.Column('doc_blob', sa.LargeBinary(), nullable=False),
    sa.Column('texts_blob', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection', 'dockey', name='uq_document_chunks_collection_dockey')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_document_chunks_collection', ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_updated_at'))
        batch_op.drop_index('ix_document_chunks_collection')

    op.drop_table('document_chunks')
    # ### end Alembic commands ###
