"""initial schema

Revision ID: d5b608e3fdd6
Revises: 
Create Date: 2026-10-01 20:39:35.367110
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.models


revision: str = 'd5b608e3fdd6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'researcher', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'archived', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('active_project_id', sa.String(length=36), nullable=True),
    sa.Column('last_action_type', sa.String(length=64), nullable=True),
    sa.Column('last_action_label', sa.Text(), nullable=True),
    sa.Column('last_action_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resume_note', sa.Text(), nullable=True),
    sa.Column('state_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('archived_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('purged_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_research_sessions_user_status', ['user_id', 'status'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('project_draft', 'project_data', 'temp_literature', 'notes', 'supplementary', 'global_knowledge', name='documentcategory', native_enum=False), nullable=False),
    sa.Column('visibility', sa.Enum('global_', 'session', name='documentvisibility', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsing', 'ready', 'error', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('dockey', sa.String(length=64), nullable=True),
    sa.Column('docname', sa.String(length=255), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('chunks_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_dockey'), ['dockey'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_docname'), ['docname'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index('ix_documents_session_category', ['session_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_documents_visibility_status', ['visibility', 'status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('hybrid', 'project_focus', 'session_only', 'global_only', name='searchmode', native_enum=False), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('token_counts', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_messages_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('target_journal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('planning', 'drafting', 'reviewing', 'done', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_session_id'), ['session_id'], unique=False)

    op.create_table('document_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('target_document_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.Enum('reference', 'data', 'draft', name='projectdocrole', native_enum=False), nullable=True),
    sa.Column('relation', sa.Enum('cites', 'supports', 'contradicts', 'uses', name='relationtype', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'project_id', 'target_document_id', name='uq_document_link')
    )
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_links_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_links_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_links_session_id'))
        batch_op.drop_index(batch_op.f('ix_document_links_project_id'))
        batch_op.drop_index(batch_op.f('ix_document_links_document_id'))

    op.drop_table('document_links')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_session_id'))

    op.drop_table('projects')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index('ix_messages_session_created')
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_visibility_status')
        batch_op.drop_index(batch_op.f('ix_documents_session_id'))
        batch_op.drop_index('ix_documents_session_category')
        batch_op.drop_index(batch_op.f('ix_documents_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_docname'))
        batch_op.drop_index(batch_op.f('ix_documents_dockey'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_research_sessions_user_status')
        batch_op.drop_index(batch_op.f('ix_research_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_expires_at'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
